using System.Text.Json.Nodes;
using Bennewitz.Ninja.ClaudeForge.Core.FileIO;
using Bennewitz.Ninja.ClaudeForge.Core.Settings;

namespace Bennewitz.Ninja.ClaudeForge.Core.Tests.FileIO;

/// <summary>
/// Error-path coverage for <see cref="ConfigFileLoader.SaveAsync"/>.
/// the success path is covered by integration
/// tests, but the read-only guard, the temp-file cleanup, and the
/// header-comment branches were under-tested.  These tests use real-disk
/// fixtures (no IO-mocking shim exists for this static API) to exercise
/// each branch deterministically.
/// </summary>
[TestClass]
public sealed class ConfigFileLoaderSaveErrorTests
{
    private string _sandbox = null!;

    [TestInitialize]
    public void Init()
    {
        _sandbox = Path.Combine(Path.GetTempPath(), $"cfl-save-{Guid.NewGuid():N}");
        Directory.CreateDirectory(_sandbox);
    }

    [TestCleanup]
    public void Cleanup()
    {
        if (!Directory.Exists(_sandbox))
        {
            return;
        }

        try
        {
            Directory.Delete(_sandbox, recursive: true);
        }
        catch (IOException)
        {
            /* AV / file-watcher transient lock — leave for OS reaper */
        }
        catch (UnauthorizedAccessException)
        {
            /* same */
        }
    }

    private SettingsDocument NewDoc(string filePath, bool isReadOnly = false)
    {
        JsonObject root = new() { ["model"] = "sonnet", ["verbose"] = true };
        return new SettingsDocument(ConfigScope.User, filePath, root, isReadOnly);
    }

    // ── ReadOnly guard ───────────────────────────────────────────────

    [TestMethod]
    public async Task SaveAsync_ReadOnlyDocument_ThrowsInvalidOp()
    {
        string path = Path.Combine(_sandbox, "ro.json");
        SettingsDocument doc = NewDoc(path, isReadOnly: true);

        InvalidOperationException ex = await Assert.ThrowsExceptionAsync<InvalidOperationException>(() => ConfigFileLoader.SaveAsync(doc));

        StringAssert.Contains(ex.Message, "read-only");
        StringAssert.Contains(ex.Message, path);
        Assert.IsFalse(File.Exists(path),
            "Read-only guard must throw before touching disk.");
    }

    // ── Happy paths ──────────────────────────────────────────────────

    [TestMethod]
    public async Task SaveAsync_NonExistentDirectory_CreatesIt()
    {
        // Target is two levels deep — both directories must be created on the fly
        // because Directory.CreateDirectory is recursive.
        string nestedDir = Path.Combine(_sandbox, "deep", "nested");
        string path = Path.Combine(nestedDir, "settings.json");
        Assert.IsFalse(Directory.Exists(nestedDir), "Pre-condition: directory must not exist.");

        await ConfigFileLoader.SaveAsync(NewDoc(path));

        Assert.IsTrue(Directory.Exists(nestedDir), "Save must create the missing directory.");
        Assert.IsTrue(File.Exists(path), "Save must produce the destination file.");
    }

    [TestMethod]
    public async Task SaveAsync_HappyPath_MarksDocumentClean()
    {
        string path = Path.Combine(_sandbox, "clean.json");
        SettingsDocument doc = NewDoc(path);

        // SettingsDocument starts clean; flip the latch directly via the
        // internal MarkDirty seam (InternalsVisibleTo grants Test access)
        // so we have a meaningful "MarkClean" assertion below.
        doc.MarkDirty();
        Assert.IsTrue(doc.IsDirty, "Pre-condition: MarkDirty must flip the dirty latch.");

        await ConfigFileLoader.SaveAsync(doc);

        Assert.IsFalse(doc.IsDirty,
            "After a successful SaveAsync, the document must be marked clean.");
    }

    [TestMethod]
    public async Task SaveAsync_HeaderComment_AppearsAtTopOfFile()
    {
        string path = Path.Combine(_sandbox, "header.json");
        SettingsDocument doc = NewDoc(path);

        await ConfigFileLoader.SaveAsync(doc, headerComment: "Generated by ClaudeForge");

        string contents = await File.ReadAllTextAsync(path);
        StringAssert.Contains(contents, "Generated by ClaudeForge");
        // The "//" key must precede the data keys in the serialized form.
        int commentIdx = contents.IndexOf("\"//\"");
        int modelIdx = contents.IndexOf("\"model\"");
        Assert.IsTrue(commentIdx >= 0, "// header key must be present.");
        Assert.IsTrue(modelIdx > commentIdx,
            "// header key must serialise BEFORE the data keys.");
    }

    [TestMethod]
    public async Task SaveAsync_HeaderComment_OverwritesStaleHeaderInRoot()
    {
        // The serialiser drops any existing "//" key in Root and replaces it with
        // the headerComment passed in. This protects against stale stamps that
        // would otherwise accumulate across repeat saves.
        string path = Path.Combine(_sandbox, "stale.json");
        JsonObject root = new()
        {
            ["//"] = "stale-stamp-from-disk",
            ["model"] = "sonnet",
        };
        SettingsDocument doc = new(ConfigScope.User, path, root, isReadOnly: false);

        await ConfigFileLoader.SaveAsync(doc, headerComment: "fresh-stamp");

        string contents = await File.ReadAllTextAsync(path);
        StringAssert.Contains(contents, "fresh-stamp");
        Assert.IsFalse(contents.Contains("stale-stamp-from-disk"),
            "Stale '//' key in Root must NOT survive into the serialised output.");
    }

    [TestMethod]
    public async Task SaveAsync_NoHeaderComment_DoesNotEmitMetadataKey()
    {
        string path = Path.Combine(_sandbox, "no-header.json");
        SettingsDocument doc = NewDoc(path);

        await ConfigFileLoader.SaveAsync(doc, headerComment: null);

        string contents = await File.ReadAllTextAsync(path);
        Assert.IsFalse(contents.Contains("\"//\""),
            "Without a header comment, the // metadata key must not appear in the file.");
    }

    // ── Failure path: temp-file cleanup on move failure ───────────────

    [TestMethod]
    public async Task SaveAsync_DestinationIsDirectory_ThrowsAndCleansUpTempFile()
    {
        // Create a DIRECTORY at the target path — File.Move into a directory-name
        // is rejected on every OS so the catch block runs deterministically.
        string path = Path.Combine(_sandbox, "blocked.json");
        Directory.CreateDirectory(path);
        Assert.IsTrue(Directory.Exists(path), "Pre-condition: target must be a directory.");

        SettingsDocument doc = NewDoc(path);

        // Windows raises UnauthorizedAccessException when File.Move's destination
        // is a directory; Linux/macOS raise IOException for the same scenario.
        // Both inherit SystemException — the test pins the catch + cleanup
        // contract, not the exact subtype.
        Exception? caught = null;
        try
        {
            await ConfigFileLoader.SaveAsync(doc);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            caught = ex;
        }

        Assert.IsNotNull(caught,
            "SaveAsync must throw IOException or UnauthorizedAccessException when the "
            + "destination path resolves to an existing directory.");

        // Verify the temp file was cleaned up — sandbox should contain only our directory.
        List<string> leakedTemps = Directory.EnumerateFiles(_sandbox, "blocked.json.tmp-*").ToList();
        Assert.AreEqual(0, leakedTemps.Count,
            "Temp file must be cleaned up after Move failure. Leaked: "
            + string.Join(", ", leakedTemps));
    }

    // ── Cancellation ─────────────────────────────────────────────────

    [TestMethod]
    public async Task SaveAsync_AlreadyCancelledToken_ThrowsAndDoesNotWriteFile()
    {
        string path = Path.Combine(_sandbox, "cancelled.json");
        SettingsDocument doc = NewDoc(path);

        using CancellationTokenSource cts = new();
        await cts.CancelAsync(); // pre-cancel so WriteAllTextAsync sees the token already faulted

        await Assert.ThrowsExceptionAsync<TaskCanceledException>(() => ConfigFileLoader.SaveAsync(doc, ct: cts.Token));

        Assert.IsFalse(File.Exists(path),
            "Cancelled save must not leave a destination file behind.");
        List<string> leakedTemps = Directory.EnumerateFiles(_sandbox, "cancelled.json.tmp-*").ToList();
        Assert.AreEqual(0, leakedTemps.Count,
            "Cancelled save's temp file must be cleaned up by the catch block.");
    }
}