//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bennewitz.Ninja.ClaudeForge.Avalonia.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bennewitz.Ninja.ClaudeForge.Avalonia.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string PermBuilderInvalid {
            get { return ResourceManager.GetString("PermBuilderInvalid", resourceCulture); }
        }

        public static string PermBuilderGlossInvalid {
            get { return ResourceManager.GetString("PermBuilderGlossInvalid", resourceCulture); }
        }

        public static string PermBuilderAddedFmt {
            get { return ResourceManager.GetString("PermBuilderAddedFmt", resourceCulture); }
        }

        public static string PermBuilderCollisionConflict {
            get { return ResourceManager.GetString("PermBuilderCollisionConflict", resourceCulture); }
        }

        public static string PermBuilderCollisionRedundant {
            get { return ResourceManager.GetString("PermBuilderCollisionRedundant", resourceCulture); }
        }

        public static string PermBuilderGlossShellAll {
            get { return ResourceManager.GetString("PermBuilderGlossShellAll", resourceCulture); }
        }

        public static string PermBuilderGlossShellPrefix {
            get { return ResourceManager.GetString("PermBuilderGlossShellPrefix", resourceCulture); }
        }

        public static string PermBuilderGlossShellExact {
            get { return ResourceManager.GetString("PermBuilderGlossShellExact", resourceCulture); }
        }

        public static string PermBuilderGlossPathAll {
            get { return ResourceManager.GetString("PermBuilderGlossPathAll", resourceCulture); }
        }

        public static string PermBuilderGlossPathRecursive {
            get { return ResourceManager.GetString("PermBuilderGlossPathRecursive", resourceCulture); }
        }

        public static string PermBuilderGlossPathExact {
            get { return ResourceManager.GetString("PermBuilderGlossPathExact", resourceCulture); }
        }

        public static string PermBuilderGlossWebAll {
            get { return ResourceManager.GetString("PermBuilderGlossWebAll", resourceCulture); }
        }

        public static string PermBuilderGlossWebDomain {
            get { return ResourceManager.GetString("PermBuilderGlossWebDomain", resourceCulture); }
        }

        public static string PermBuilderGlossMcpServer {
            get { return ResourceManager.GetString("PermBuilderGlossMcpServer", resourceCulture); }
        }

        public static string PermBuilderGlossMcpTool {
            get { return ResourceManager.GetString("PermBuilderGlossMcpTool", resourceCulture); }
        }

        public static string PermBuilderGlossAgentAll {
            get { return ResourceManager.GetString("PermBuilderGlossAgentAll", resourceCulture); }
        }

        public static string PermBuilderGlossAgentNamed {
            get { return ResourceManager.GetString("PermBuilderGlossAgentNamed", resourceCulture); }
        }

        public static string PermOutcomeAllow {
            get { return ResourceManager.GetString("PermOutcomeAllow", resourceCulture); }
        }

        public static string PermOutcomeAsk {
            get { return ResourceManager.GetString("PermOutcomeAsk", resourceCulture); }
        }

        public static string PermOutcomeDeny {
            get { return ResourceManager.GetString("PermOutcomeDeny", resourceCulture); }
        }

        public static string PermOutcomeDefault {
            get { return ResourceManager.GetString("PermOutcomeDefault", resourceCulture); }
        }

        public static string PermTesterDefaultModeUnset {
            get { return ResourceManager.GetString("PermTesterDefaultModeUnset", resourceCulture); }
        }

        public static string PermTesterExplainDefault {
            get { return ResourceManager.GetString("PermTesterExplainDefault", resourceCulture); }
        }

        public static string PermTesterExplainMatched {
            get { return ResourceManager.GetString("PermTesterExplainMatched", resourceCulture); }
        }

        public static string PermTesterExplainMatchedScoped {
            get { return ResourceManager.GetString("PermTesterExplainMatchedScoped", resourceCulture); }
        }

        public static string PermTesterDecidingPart {
            get { return ResourceManager.GetString("PermTesterDecidingPart", resourceCulture); }
        }

        public static string PermTesterReadOnlyNote {
            get { return ResourceManager.GetString("PermTesterReadOnlyNote", resourceCulture); }
        }

        public static string PermEduHeading {
            get { return ResourceManager.GetString("PermEduHeading", resourceCulture); }
        }

        public static string PermEduIntro {
            get { return ResourceManager.GetString("PermEduIntro", resourceCulture); }
        }

        public static string PermEduPrecedenceHeading {
            get { return ResourceManager.GetString("PermEduPrecedenceHeading", resourceCulture); }
        }

        public static string PermEduPrecedenceBody {
            get { return ResourceManager.GetString("PermEduPrecedenceBody", resourceCulture); }
        }

        public static string PermEduPerToolHeading {
            get { return ResourceManager.GetString("PermEduPerToolHeading", resourceCulture); }
        }

        public static string PermEduPerToolBody {
            get { return ResourceManager.GetString("PermEduPerToolBody", resourceCulture); }
        }

        public static string PermEduMistakesHeading {
            get { return ResourceManager.GetString("PermEduMistakesHeading", resourceCulture); }
        }

        public static string PermEduMistake1 {
            get { return ResourceManager.GetString("PermEduMistake1", resourceCulture); }
        }

        public static string PermEduMistake2 {
            get { return ResourceManager.GetString("PermEduMistake2", resourceCulture); }
        }

        public static string PermEduMistake3 {
            get { return ResourceManager.GetString("PermEduMistake3", resourceCulture); }
        }

        public static string PermBuilderHeading {
            get { return ResourceManager.GetString("PermBuilderHeading", resourceCulture); }
        }

        public static string PermBuilderHintStarShell {
            get { return ResourceManager.GetString("PermBuilderHintStarShell", resourceCulture); }
        }

        public static string PermBuilderHintWebDomain {
            get { return ResourceManager.GetString("PermBuilderHintWebDomain", resourceCulture); }
        }

        public static string PermBuilderHintMcpAll {
            get { return ResourceManager.GetString("PermBuilderHintMcpAll", resourceCulture); }
        }

        public static string PermBuilderHintMcpOne {
            get { return ResourceManager.GetString("PermBuilderHintMcpOne", resourceCulture); }
        }

        public static string PermBuilderHintStarPath {
            get { return ResourceManager.GetString("PermBuilderHintStarPath", resourceCulture); }
        }

        public static string PermBuilderHintDoubleStarPath {
            get { return ResourceManager.GetString("PermBuilderHintDoubleStarPath", resourceCulture); }
        }

        public static string PermBuilderHintQuestionPath {
            get { return ResourceManager.GetString("PermBuilderHintQuestionPath", resourceCulture); }
        }

        public static string PermBuilderHintGroupWildcards {
            get { return ResourceManager.GetString("PermBuilderHintGroupWildcards", resourceCulture); }
        }

        public static string PermBuilderHintGroupAnchors {
            get { return ResourceManager.GetString("PermBuilderHintGroupAnchors", resourceCulture); }
        }

        public static string PermBuilderHintAnchorProject {
            get { return ResourceManager.GetString("PermBuilderHintAnchorProject", resourceCulture); }
        }

        public static string PermBuilderHintAnchorAbsolute {
            get { return ResourceManager.GetString("PermBuilderHintAnchorAbsolute", resourceCulture); }
        }

        public static string PermBuilderHintAnchorHome {
            get { return ResourceManager.GetString("PermBuilderHintAnchorHome", resourceCulture); }
        }

        public static string PermBuilderHintAnchorCwd {
            get { return ResourceManager.GetString("PermBuilderHintAnchorCwd", resourceCulture); }
        }

        public static string PermBuilderToolLabel {
            get { return ResourceManager.GetString("PermBuilderToolLabel", resourceCulture); }
        }

        public static string PermBuilderToolTip {
            get { return ResourceManager.GetString("PermBuilderToolTip", resourceCulture); }
        }

        public static string PermBuilderCommandLabel {
            get { return ResourceManager.GetString("PermBuilderCommandLabel", resourceCulture); }
        }

        public static string PermBuilderCommandTip {
            get { return ResourceManager.GetString("PermBuilderCommandTip", resourceCulture); }
        }

        public static string PermBuilderPrefixLabel {
            get { return ResourceManager.GetString("PermBuilderPrefixLabel", resourceCulture); }
        }

        public static string PermBuilderPrefixTip {
            get { return ResourceManager.GetString("PermBuilderPrefixTip", resourceCulture); }
        }

        public static string PermBuilderPathLabel {
            get { return ResourceManager.GetString("PermBuilderPathLabel", resourceCulture); }
        }

        public static string PermBuilderPathTip {
            get { return ResourceManager.GetString("PermBuilderPathTip", resourceCulture); }
        }

        public static string PermBuilderBrowseFile {
            get { return ResourceManager.GetString("PermBuilderBrowseFile", resourceCulture); }
        }

        public static string PermBuilderBrowseFolder {
            get { return ResourceManager.GetString("PermBuilderBrowseFolder", resourceCulture); }
        }

        public static string PermBuilderRecursiveLabel {
            get { return ResourceManager.GetString("PermBuilderRecursiveLabel", resourceCulture); }
        }

        public static string PermBuilderRecursiveTip {
            get { return ResourceManager.GetString("PermBuilderRecursiveTip", resourceCulture); }
        }

        public static string PermBuilderDomainLabel {
            get { return ResourceManager.GetString("PermBuilderDomainLabel", resourceCulture); }
        }

        public static string PermBuilderDomainTip {
            get { return ResourceManager.GetString("PermBuilderDomainTip", resourceCulture); }
        }

        public static string PermBuilderMcpServerLabel {
            get { return ResourceManager.GetString("PermBuilderMcpServerLabel", resourceCulture); }
        }

        public static string PermBuilderMcpServerTip {
            get { return ResourceManager.GetString("PermBuilderMcpServerTip", resourceCulture); }
        }

        public static string PermBuilderMcpAllToolsLabel {
            get { return ResourceManager.GetString("PermBuilderMcpAllToolsLabel", resourceCulture); }
        }

        public static string PermBuilderMcpToolLabel {
            get { return ResourceManager.GetString("PermBuilderMcpToolLabel", resourceCulture); }
        }

        public static string PermBuilderMcpToolTip {
            get { return ResourceManager.GetString("PermBuilderMcpToolTip", resourceCulture); }
        }

        public static string PermBuilderAgentLabel {
            get { return ResourceManager.GetString("PermBuilderAgentLabel", resourceCulture); }
        }

        public static string PermBuilderAgentTip {
            get { return ResourceManager.GetString("PermBuilderAgentTip", resourceCulture); }
        }

        public static string PermBuilderPreviewLabel {
            get { return ResourceManager.GetString("PermBuilderPreviewLabel", resourceCulture); }
        }

        public static string PermBuilderPreviewTip {
            get { return ResourceManager.GetString("PermBuilderPreviewTip", resourceCulture); }
        }

        public static string PermBuilderAddAllowTip {
            get { return ResourceManager.GetString("PermBuilderAddAllowTip", resourceCulture); }
        }

        public static string PermBuilderAddAskTip {
            get { return ResourceManager.GetString("PermBuilderAddAskTip", resourceCulture); }
        }

        public static string PermBuilderAddDenyTip {
            get { return ResourceManager.GetString("PermBuilderAddDenyTip", resourceCulture); }
        }

        public static string PermTesterHeading {
            get { return ResourceManager.GetString("PermTesterHeading", resourceCulture); }
        }

        public static string PermTesterToolLabel {
            get { return ResourceManager.GetString("PermTesterToolLabel", resourceCulture); }
        }

        public static string PermTesterCommandLabel {
            get { return ResourceManager.GetString("PermTesterCommandLabel", resourceCulture); }
        }

        public static string PermTesterPathLabel {
            get { return ResourceManager.GetString("PermTesterPathLabel", resourceCulture); }
        }

        public static string PermTesterUrlLabel {
            get { return ResourceManager.GetString("PermTesterUrlLabel", resourceCulture); }
        }

        public static string PermTesterMcpServerLabel {
            get { return ResourceManager.GetString("PermTesterMcpServerLabel", resourceCulture); }
        }

        public static string PermTesterMcpToolLabel {
            get { return ResourceManager.GetString("PermTesterMcpToolLabel", resourceCulture); }
        }

        public static string PermTesterAgentLabel {
            get { return ResourceManager.GetString("PermTesterAgentLabel", resourceCulture); }
        }

        public static string PermTesterMergedLabel {
            get { return ResourceManager.GetString("PermTesterMergedLabel", resourceCulture); }
        }

        public static string PermTesterMergedTip {
            get { return ResourceManager.GetString("PermTesterMergedTip", resourceCulture); }
        }

        public static string PermTesterResultHeading {
            get { return ResourceManager.GetString("PermTesterResultHeading", resourceCulture); }
        }

        public static string PermTesterNoInput {
            get { return ResourceManager.GetString("PermTesterNoInput", resourceCulture); }
        }

        public static string PermTesterScopeLabel {
            get { return ResourceManager.GetString("PermTesterScopeLabel", resourceCulture); }
        }

        public static string PermTesterInputTip {
            get { return ResourceManager.GetString("PermTesterInputTip", resourceCulture); }
        }
    }
}
