using System.Text.Json.Nodes;
using Bennewitz.Ninja.AgentForge.Core.FileIO;
using Bennewitz.Ninja.AgentForge.Core.Settings;

namespace Bennewitz.Ninja.AgentForge.Core.Tests.FileIO;

/// <summary>
/// Error-path coverage for <see cref="ConfigFileLoader.SaveAsync"/>.
/// the success path is covered by integration
/// tests, but the read-only guard, the temp-file cleanup, and the
/// header-comment branches were under-tested.  These tests use real-disk
/// fixtures (no IO-mocking shim exists for this static API) to exercise
/// each branch deterministically.
/// </summary>
public sealed class ConfigFileLoaderSaveErrorTests : IDisposable
{
    private string _sandbox = null!;

    public ConfigFileLoaderSaveErrorTests() => Init();

    private void Init()
    {
        _sandbox = Path.Combine(Path.GetTempPath(), $"cfl-save-{Guid.NewGuid():N}");
        Directory.CreateDirectory(_sandbox);
    }

    private void Cleanup()
    {
        if (!Directory.Exists(_sandbox))
        {
            return;
        }

        try
        {
            Directory.Delete(_sandbox, recursive: true);
        }
        catch (IOException)
        {
            /* AV / file-watcher transient lock — leave for OS reaper */
        }
        catch (UnauthorizedAccessException)
        {
            /* same */
        }
    }

    public void Dispose()
    {
        Cleanup();
        GC.SuppressFinalize(this);
    }

    private SettingsDocument NewDoc(string filePath, bool isReadOnly = false)
    {
        JsonObject root = new() { ["model"] = "sonnet", ["verbose"] = true };
        return new SettingsDocument(ConfigScope.User, filePath, root, isReadOnly);
    }

    // ── ReadOnly guard ───────────────────────────────────────────────

    [Fact]
    public async Task SaveAsync_ReadOnlyDocument_ThrowsInvalidOp()
    {
        string path = Path.Combine(_sandbox, "ro.json");
        SettingsDocument doc = NewDoc(path, isReadOnly: true);

        InvalidOperationException ex = await Assert.ThrowsAsync<InvalidOperationException>(() => ConfigFileLoader.SaveAsync(doc, ct: TestContext.Current.CancellationToken));

        OrdinalAssert.Contains("read-only", ex.Message);
        OrdinalAssert.Contains(path, ex.Message);
        Assert.False(File.Exists(path),
            "Read-only guard must throw before touching disk.");
    }

    // ── Happy paths ──────────────────────────────────────────────────

    [Fact]
    public async Task SaveAsync_NonExistentDirectory_CreatesIt()
    {
        // Target is two levels deep — both directories must be created on the fly
        // because Directory.CreateDirectory is recursive.
        string nestedDir = Path.Combine(_sandbox, "deep", "nested");
        string path = Path.Combine(nestedDir, "settings.json");
        Assert.False(Directory.Exists(nestedDir), "Pre-condition: directory must not exist.");

        await ConfigFileLoader.SaveAsync(NewDoc(path), ct: TestContext.Current.CancellationToken);

        Assert.True(Directory.Exists(nestedDir), "Save must create the missing directory.");
        Assert.True(File.Exists(path), "Save must produce the destination file.");
    }

    [Fact]
    public async Task SaveAsync_HappyPath_MarksDocumentClean()
    {
        string path = Path.Combine(_sandbox, "clean.json");
        SettingsDocument doc = NewDoc(path);

        // SettingsDocument starts clean; flip the latch directly via the
        // internal MarkDirty seam (InternalsVisibleTo grants Test access)
        // so we have a meaningful "MarkClean" assertion below.
        doc.MarkDirty();
        Assert.True(doc.IsDirty, "Pre-condition: MarkDirty must flip the dirty latch.");

        await ConfigFileLoader.SaveAsync(doc, ct: TestContext.Current.CancellationToken);

        Assert.False(doc.IsDirty,
            "After a successful SaveAsync, the document must be marked clean.");
    }

    /// <summary>
    /// The stamp is written when the document has real changes.
    /// </summary>
    /// <remarks>
    /// Previously this test saved a <i>clean</i> document and expected a stamp, because
    /// the stamp used to be unconditional. Phase 2 made it conditional on
    /// <see cref="SettingsDocument.HasActualChanges"/> so that a no-op save can be
    /// byte-identical — the stamp embeds <c>DateTime.Now</c> to the second, so writing it
    /// unconditionally made "no edits, identical bytes" impossible to state honestly.
    /// The test now sets up the change that earns the stamp; see
    /// <see cref="SaveAsync_CleanDocument_WritesNoStampAndLeavesBytesIdentical"/> for the
    /// other half of the contract.
    /// </remarks>
    [Fact]
    public async Task SaveAsync_HeaderComment_AppearsAtTopOfFile_WhenSomethingChanged()
    {
        string path = Path.Combine(_sandbox, "header.json");
        SettingsDocument doc = NewDoc(path);
        doc.Root["model"] = "opus"; // a real change, so the stamp is earned

        await ConfigFileLoader.SaveAsync(doc, headerComment: "Generated by ClaudeForge", ct: TestContext.Current.CancellationToken);

        string contents = await File.ReadAllTextAsync(path, TestContext.Current.CancellationToken);
        OrdinalAssert.Contains("Generated by ClaudeForge", contents);
        // The "//" key must precede the data keys in the serialized form.
        int commentIdx = contents.IndexOf("\"//\"", StringComparison.Ordinal);
        int modelIdx = contents.IndexOf("\"model\"", StringComparison.Ordinal);
        Assert.True(commentIdx >= 0, "// header key must be present.");
        Assert.True(modelIdx > commentIdx,
            "// header key must serialise BEFORE the data keys.");
    }

    [Fact]
    public async Task SaveAsync_HeaderComment_OverwritesStaleHeaderInRoot()
    {
        // A fresh stamp replaces any existing one rather than accumulating. Same
        // conditional-stamp caveat as above: the document needs a real change for the
        // stamp to be written at all.
        string path = Path.Combine(_sandbox, "stale.json");
        JsonObject root = new()
        {
            ["//"] = "stale-stamp-from-disk",
            ["model"] = "sonnet",
        };
        SettingsDocument doc = new(ConfigScope.User, path, root, isReadOnly: false);
        doc.Root["model"] = "opus";

        await ConfigFileLoader.SaveAsync(doc, headerComment: "fresh-stamp", ct: TestContext.Current.CancellationToken);

        string contents = await File.ReadAllTextAsync(path, TestContext.Current.CancellationToken);
        OrdinalAssert.Contains("fresh-stamp", contents);
        Assert.False(contents.Contains("stale-stamp-from-disk", StringComparison.Ordinal),
            "Stale '//' key in Root must NOT survive into the serialised output.");
    }

    /// <summary>
    /// The other half of the conditional-stamp contract, and the reason it exists: saving
    /// a document with nothing pending must not touch the file.
    /// </summary>
    /// <remarks>
    /// This is what the maintainer chose over the alternative of accepting a permanent
    /// one-line diff on every save. Without this test the conditional would be an
    /// unverified claim, and the obvious "simplification" — making the stamp
    /// unconditional again — would pass the rest of the suite.
    /// </remarks>
    [Fact]
    public async Task SaveAsync_CleanDocument_WritesNoStampAndLeavesBytesIdentical()
    {
        string path = Path.Combine(_sandbox, "clean.json");
        const string original = "{\n  // a comment worth keeping\n  \"model\": \"sonnet\"\n}";
        await File.WriteAllTextAsync(path, original, TestContext.Current.CancellationToken);

        DiscoveredFile file = new(ConfigScope.User, ConfigFileType.ClaudeCodeSettings, path,
                                  Exists: true, IsReadOnly: false);
        SettingsDocument doc = await ConfigFileLoader.LoadAsync(file, TestContext.Current.CancellationToken);

        Assert.False(doc.HasActualChanges(), "Pre-condition: nothing was edited.");

        await ConfigFileLoader.SaveAsync(doc, headerComment: "should not be written", ct: TestContext.Current.CancellationToken);

        string after = await File.ReadAllTextAsync(path, TestContext.Current.CancellationToken);
        MessageAssert.Equal(original, after,
            "A save with no pending edits must reproduce the file byte for byte — including "
            + "the comment, and without adding a timestamped stamp.");
    }

    [Fact]
    public async Task SaveAsync_NoHeaderComment_DoesNotEmitMetadataKey()
    {
        string path = Path.Combine(_sandbox, "no-header.json");
        SettingsDocument doc = NewDoc(path);

        await ConfigFileLoader.SaveAsync(doc, headerComment: null, ct: TestContext.Current.CancellationToken);

        string contents = await File.ReadAllTextAsync(path, TestContext.Current.CancellationToken);
        Assert.False(contents.Contains("\"//\""),
            "Without a header comment, the // metadata key must not appear in the file.");
    }

    // ── Failure path: temp-file cleanup on move failure ───────────────

    [Fact]
    public async Task SaveAsync_DestinationIsDirectory_ThrowsAndCleansUpTempFile()
    {
        // Create a DIRECTORY at the target path — File.Move into a directory-name
        // is rejected on every OS so the catch block runs deterministically.
        string path = Path.Combine(_sandbox, "blocked.json");
        Directory.CreateDirectory(path);
        Assert.True(Directory.Exists(path), "Pre-condition: target must be a directory.");

        SettingsDocument doc = NewDoc(path);

        // Windows raises UnauthorizedAccessException when File.Move's destination
        // is a directory; Linux/macOS raise IOException for the same scenario.
        // Both inherit SystemException — the test pins the catch + cleanup
        // contract, not the exact subtype.
        Exception? caught = null;
        try
        {
            await ConfigFileLoader.SaveAsync(doc, ct: TestContext.Current.CancellationToken);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            caught = ex;
        }

        MessageAssert.NotNull(caught,
            "SaveAsync must throw IOException or UnauthorizedAccessException when the "
            + "destination path resolves to an existing directory.");

        // Verify the temp file was cleaned up — sandbox should contain only our directory.
        List<string> leakedTemps = Directory.EnumerateFiles(_sandbox, "blocked.json.tmp-*").ToList();
        MessageAssert.Equal(0, leakedTemps.Count,
            "Temp file must be cleaned up after Move failure. Leaked: "
            + string.Join(", ", leakedTemps));
    }

    // ── Cancellation ─────────────────────────────────────────────────

    [Fact]
    public async Task SaveAsync_AlreadyCancelledToken_ThrowsAndDoesNotWriteFile()
    {
        string path = Path.Combine(_sandbox, "cancelled.json");
        SettingsDocument doc = NewDoc(path);

        using CancellationTokenSource cts = new();
        await cts.CancelAsync(); // pre-cancel so WriteAllTextAsync sees the token already faulted

        await Assert.ThrowsAsync<TaskCanceledException>(() => ConfigFileLoader.SaveAsync(doc, ct: cts.Token));

        Assert.False(File.Exists(path),
            "Cancelled save must not leave a destination file behind.");
        List<string> leakedTemps = Directory.EnumerateFiles(_sandbox, "cancelled.json.tmp-*").ToList();
        MessageAssert.Equal(0, leakedTemps.Count,
            "Cancelled save's temp file must be cleaned up by the catch block.");
    }
}